site_name: Advanced Peripherals
site_url: 'https://docs.srendi.de/'

nav:
    - 'Home': 'index.md'
    - 'Peripherals':
      - 'Chat Box': 'peripherals/chat_box.md'
      - 'Environment Detector': 'peripherals/environment_detector.md'
      - 'Player Detector': 'peripherals/player_detector.md'
      - 'Me Bridge': 'peripherals/me_bridge.md'
      - 'Rs Bridge': 'peripherals/rs_bridge.md'
      - 'Energy Detector': 'peripherals/energy_detector.md'
      - 'AR Controller': 'peripherals/ar_controller.md'
      - 'Inventory Manager': 'peripherals/inventory_manager.md'
      - 'Redstone Integrator': 'peripherals/redstone_integrator.md'
      - 'Block Reader': 'peripherals/block_reader.md'
      - 'NBT Storage': 'peripherals/nbt_storage.md'
      - 'Geo Scanner': 'peripherals/geo_scanner.md'
    - 'Mod Integrations':
      - 'How does it work?': 'integrations/getstarted.md'
      - 'Minecraft':
        - 'Beacon': 'integrations/mc/beacon.md'
      - 'Mekanism':
        - 'Fission Reactor': 'integrations/mekanism/fission.md'
        - 'Fusion Reactor': 'integrations/mekanism/fusion.md'
        - 'Boiler': 'integrations/mekanism/boiler.md'
        - 'Generic Machine': 'integrations/mekanism/generic.md'
        - 'Turbine': 'integrations/mekanism/turbine.md'
        - 'Induction Matrix': 'integrations/mekanism/induction.md'
        - 'Digital Miner': 'integrations/mekanism/digital_miner.md'
        - 'Chemical Tank': 'integrations/mekanism/chemical.md'
      - 'Botania':
        - 'Mana generating flower': 'integrations/botania/flower.md'
        - 'Mana Pool': 'integrations/botania/pool.md'
        - 'Mana Spreader': 'integrations/botania/spreader.md'
      - 'Immersive Engineering':
        - 'Capacitor': 'integrations/ie/capacitor.md'
        - 'Redstone Probe': 'integrations/ie/probe.md'
        - 'Redstone Wire Connector': 'integrations/ie/connector.md'
      - 'Storage Drawers':
        - 'Drawer': 'integrations/sd/drawer.md'
      - 'Integrated Dynamics':
        - 'Variable Store': 'integrations/id/variable_store.md'
    - 'Metaphysics':
      - 'Cooldowns and fuel consumption': 'metaphysics/cooldowns_and_fuel_consumption.md'
      - 'Weak automata': 'metaphysics/weak_automata.md'
      - 'Overpowered automata': 'metaphysics/overpowered_automata.md'
      - 'End automata': 'metaphysics/end_automata.md'
      - 'Husbandry automata': 'metaphysics/husbandry_automata.md'
    - 'Turtles':
      - 'Chunky Turtle': 'turtles/chunky_turtle.md'
      - 'Environment Turtle': 'turtles/environment_turtle.md'
      - 'Player Turtle': 'turtles/player_turtle.md'
      - 'Chatty Turtle': 'turtles/chatty_turtle.md'
      - 'Geoscanning Turtle': 'turtles/geo_scanner_turtle.md'
    - 'Items':
      - 'Chunk Controller': 'items/chunk_controller.md'
      - 'Pocket Computer': 'items/pocket_computer.md'
      - 'AR Goggles': 'items/ar_goggles.md'
      - 'Computer Tool': 'items/computer_tool.md'
      - 'Memory Card': 'items/memory_card.md'
    - 'Utilities and Others':
      - 'Item parameter for ME/RS Bridge': 'othersandutilities/item_parameter.md'
theme:
    name: material
    features:
      - navigation.top
    palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: en

repo_url: https://github.com/Seniorendi/Advanced-Peripherals-Documentation
repo_name: Seniorendi/Advanced-Peripherals-Documentation
edit_uri: edit/main/docs/

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - attr_list
    - def_list
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
