site_name: Advanced Peripherals
site_url: 'https://docs.srendi.de/'

nav:
    - 'Home': 'index.md'
    - '1.16':
      - 'Peripherals':
        - 'Chat Box': '1.16/peripherals/chat_box.md'
        - 'Environment Detector': '1.16/peripherals/environment_detector.md'
        - 'Player Detector': '1.16/peripherals/player_detector.md'
        - 'Me Bridge': '1.16/peripherals/me_bridge.md'
        - 'Rs Bridge': '1.16/peripherals/rs_bridge.md'
        - 'Energy Detector': '1.16/peripherals/energy_detector.md'
        - 'AR Controller': '1.16/peripherals/ar_controller.md'
        - 'Inventory Manager': '1.16/peripherals/inventory_manager.md'
        - 'Redstone Integrator': '1.16/peripherals/redstone_integrator.md'
        - 'Block Reader': '1.16/peripherals/block_reader.md'
        - 'NBT Storage': '1.16/peripherals/nbt_storage.md'
        - 'Geo Scanner': '1.16/peripherals/geo_scanner.md'
        - 'Colony Integrator': '1.16/peripherals/colony_integrator.md'
      - 'Mod Integrations':
        - 'How does it work?': '1.16/integrations/getstarted.md'
        - 'Minecraft':
          - 'Beacon': '1.16/integrations/mc/beacon.md'
          - 'Noteblock': '1.16/integrations/mc/noteblock.md'
        - 'Draconic Evolution':
          - 'Energy Core': '1.16/integrations/draconic/energy_core.md'
          - 'Reactor': '1.16/integrations/draconic/reactor.md'
        - 'Mekanism':
          - 'Fission Reactor': '1.16/integrations/mekanism/fission.md'
          - 'Fusion Reactor': '1.16/integrations/mekanism/fusion.md'
          - 'Boiler': '1.16/integrations/mekanism/boiler.md'
          - 'Generic Machine': '1.16/integrations/mekanism/generic.md'
          - 'Turbine': '1.16/integrations/mekanism/turbine.md'
          - 'Induction Matrix': '1.16/integrations/mekanism/induction.md'
          - 'Digital Miner': '1.16/integrations/mekanism/digital_miner.md'
          - 'Chemical Tank': '1.16/integrations/mekanism/chemical.md'
          - 'Fluid Tank': '1.16/integrations/mekanism/fluid_tank.md'
          - 'Solar Evaporation Tower': '1.16/integrations/mekanism/solar_evaporation.md'
          - 'Dynamic Tank': '1.16/integrations/mekanism/dynamic_tank.md'
          - 'Waste Barrel': '1.16/integrations/mekanism/waste_barrel.md'
          - 'Transmitters': '1.16/integrations/mekanism/transmitter.md'
        - 'Botania':
          - 'Mana generating flower': '1.16/integrations/botania/flower.md'
          - 'Mana Pool': '1.16/integrations/botania/pool.md'
          - 'Mana Spreader': '1.16/integrations/botania/spreader.md'
        - 'Immersive Engineering':
          - 'Capacitor': '1.16/integrations/ie/capacitor.md'
          - 'Redstone Probe': '1.16/integrations/ie/probe.md'
          - 'Redstone Wire Connector': '1.16/integrations/ie/connector.md'
        - 'Storage Drawers':
          - 'Drawer': '1.16/integrations/sd/drawer.md'
        - 'Integrated Dynamics':
          - 'Variable Store': '1.16/integrations/id/variable_store.md'
      - 'Metaphysics':
        - 'Cooldowns and fuel consumption': '1.16/metaphysics/cooldowns_and_fuel_consumption.md'
        - 'Weak automata': '1.16/metaphysics/weak_automata.md'
        - 'Overpowered automata': '1.16/metaphysics/overpowered_automata.md'
        - 'End automata': '1.16/metaphysics/end_automata.md'
        - 'Husbandry automata': '1.16/metaphysics/husbandry_automata.md'
      - 'Turtles':
        - 'Chunky Turtle': '1.16/turtles/chunky_turtle.md'
        - 'Environment Turtle': '1.16/turtles/environment_turtle.md'
        - 'Player Turtle': '1.16/turtles/player_turtle.md'
        - 'Chatty Turtle': '1.16/turtles/chatty_turtle.md'
        - 'Geoscanning Turtle': '1.16/turtles/geo_scanner_turtle.md'
      - 'Items':
        - 'Chunk Controller': '1.16/items/chunk_controller.md'
        - 'Pocket Computer': '1.16/items/pocket_computer.md'
        - 'AR Goggles': '1.16/items/ar_goggles.md'
        - 'Computer Tool': '1.16/items/computer_tool.md'
        - 'Memory Card': '1.16/items/memory_card.md'
      - 'Utilities and Others':
        - 'Item parameter for ME/RS Bridge': '1.16/othersandutilities/item_parameter.md'
      - 'Changelogs':
        - 'Changelog 0.7r': '1.16/changelog/0.7r.md'
    - '1.17':
      - 'Peripherals':
        - 'Chat Box': '1.17/peripherals/chat_box.md'
        - 'Environment Detector': '1.17/peripherals/environment_detector.md'
        - 'Player Detector': '1.17/peripherals/player_detector.md'
        - 'Me Bridge': '1.17/peripherals/me_bridge.md'
        - 'Energy Detector': '1.17/peripherals/energy_detector.md'
        - 'AR Controller': '1.17/peripherals/ar_controller.md'
        - 'Inventory Manager': '1.17/peripherals/inventory_manager.md'
        - 'Redstone Integrator': '1.17/peripherals/redstone_integrator.md'
        - 'Block Reader': '1.17/peripherals/block_reader.md'
        - 'NBT Storage': '1.17/peripherals/nbt_storage.md'
        - 'Geo Scanner': '1.17/peripherals/geo_scanner.md'
        - 'Colony Integrator': '1.17/peripherals/colony_integrator.md'
      - 'Mod Integrations':
        - 'How does it work?': '1.17/integrations/getstarted.md'
        - 'Minecraft':
          - 'Beacon': '1.17/integrations/mc/beacon.md'
          - 'Noteblock': '1.17/integrations/mc/noteblock.md'
      - 'Metaphysics':
        - 'Cooldowns and fuel consumption': '1.17/metaphysics/cooldowns_and_fuel_consumption.md'
        - 'Weak automata': '1.17/metaphysics/weak_automata.md'
        - 'Overpowered automata': '1.17/metaphysics/overpowered_automata.md'
        - 'End automata': '1.17/metaphysics/end_automata.md'
        - 'Husbandry automata': '1.17/metaphysics/husbandry_automata.md'
      - 'Turtles':
        - 'Chunky Turtle': '1.17/turtles/chunky_turtle.md'
        - 'Environment Turtle': '1.17/turtles/environment_turtle.md'
        - 'Player Turtle': '1.17/turtles/player_turtle.md'
        - 'Chatty Turtle': '1.17/turtles/chatty_turtle.md'
        - 'Geoscanning Turtle': '1.17/turtles/geo_scanner_turtle.md'
      - 'Items':
        - 'Chunk Controller': '1.17/items/chunk_controller.md'
        - 'Pocket Computer': '1.17/items/pocket_computer.md'
        - 'AR Goggles': '1.17/items/ar_goggles.md'
        - 'Computer Tool': '1.17/items/computer_tool.md'
        - 'Memory Card': '1.17/items/memory_card.md'
      - 'Utilities and Others':
        - 'Item parameter for ME Bridge': '1.17/othersandutilities/item_parameter.md'
      - 'Changelogs':
        - 'Changelog 0.7r': '1.17/changelog/0.7r.md'
    - '1.18':
      - 'Peripherals':
        - 'Chat Box': '1.18/peripherals/chat_box.md'
        - 'Environment Detector': '1.18/peripherals/environment_detector.md'
        - 'Player Detector': '1.18/peripherals/player_detector.md'
        - 'Me Bridge': '1.18/peripherals/me_bridge.md'
        - 'Rs Bridge': '1.18/peripherals/rs_bridge.md'
        - 'Energy Detector': '1.18/peripherals/energy_detector.md'
        - 'AR Controller': '1.18/peripherals/ar_controller.md'
        - 'Inventory Manager': '1.18/peripherals/inventory_manager.md'
        - 'Redstone Integrator': '1.18/peripherals/redstone_integrator.md'
        - 'Block Reader': '1.18/peripherals/block_reader.md'
        - 'NBT Storage': '1.18/peripherals/nbt_storage.md'
        - 'Geo Scanner': '1.18/peripherals/geo_scanner.md'
        - 'Colony Integrator': '1.18/peripherals/colony_integrator.md'
      - 'Mod Integrations':
        - 'How does it work?': '1.18/integrations/getstarted.md'
        - 'Minecraft':
          - 'Beacon': '1.18/integrations/mc/beacon.md'
          - 'Noteblock': '1.18/integrations/mc/noteblock.md'
        - 'Botania':
          - 'Flowers': '1.18/integrations/botania/flower.md'
          - 'Mana Pool': '1.18/integrations/botania/pool.md'
          - 'Mana Spreader': '1.18/integrations/botania/spreader.md'
        - 'Create':
          - 'Basin': '1.18/integrations/create/basin.md'
          - 'Blaze Burner': '1.18/integrations/create/blazeburner.md'
          - 'Fluid Tank': '1.18/integrations/create/fluidtank.md'
          - 'Mechanical Mixer': '1.18/integrations/create/mechanicalmixer.md'
          - 'Scroll value behaviour blocks': '1.18/integrations/create/scrollbehaviour.md'
      - 'Metaphysics':
        - 'Cooldowns and fuel consumption': '1.18/metaphysics/cooldowns_and_fuel_consumption.md'
        - 'Weak automata': '1.18/metaphysics/weak_automata.md'
        - 'Overpowered automata': '1.18/metaphysics/overpowered_automata.md'
        - 'End automata': '1.18/metaphysics/end_automata.md'
        - 'Husbandry automata': '1.18/metaphysics/husbandry_automata.md'
      - 'Turtles':
        - 'Chunky Turtle': '1.18/turtles/chunky_turtle.md'
        - 'Environment Turtle': '1.18/turtles/environment_turtle.md'
        - 'Player Turtle': '1.18/turtles/player_turtle.md'
        - 'Chatty Turtle': '1.18/turtles/chatty_turtle.md'
        - 'Geoscanning Turtle': '1.18/turtles/geo_scanner_turtle.md'
      - 'Items':
        - 'Chunk Controller': '1.18/items/chunk_controller.md'
        - 'Pocket Computer': '1.18/items/pocket_computer.md'
        - 'AR Goggles': '1.18/items/ar_goggles.md'
        - 'Computer Tool': '1.18/items/computer_tool.md'
        - 'Memory Card': '1.18/items/memory_card.md'
      - 'Utilities and Others':
        - 'Item parameter for ME Bridge': '1.18/othersandutilities/item_parameter.md'
      - 'Changelogs':
        - 'Changelog 0.7r': '1.18/changelog/0.7r.md'

theme:
    name: material
    features:
      - navigation.top
    palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: en

repo_url: https://github.com/Seniorendi/Advanced-Peripherals-Documentation
repo_name: Seniorendi/Advanced-Peripherals-Documentation
edit_uri: edit/main/docs/

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - pymdownx.details
    - attr_list
    - def_list
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
