[tool.poetry]
name = "advanced-peripherals-documentation"
version = "0.1.0"
description = ""
authors = ["Srendi"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.3"
python-markdown-math = "^0.8"
pyyaml = "^6.0.1"
mkdocs-glightbox = "^0.3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
